---
name: testssl.sh CI with MacOS

on:
  workflow_dispatch:
    paths-ignore:
      - 'utils/**'
      - 'doc/**'
      - 'bin/**'
      - '**.md'
      - '**.pem'
      - '**.pdf'
      - '**.html'
      - 'LICENSE'
      - 'Dockerfile'
      - 'Dockerfile-alpine'

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14

    name: PoC unit test on MacOS
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up system (perl, curl is installed already)
        run: |
          brew install socat jsonlint cpanminus
          printf "%s\n" "----------"
          mv -v /opt/homebrew/bin/openssl /opt/homebrew/bin/openssl.NOPE
          printf "%s\n" "----------"
          perl -V
          printf "%s\n" "----------"
          curl --version
          printf "%s\n" "----------"
          openssl version -a
          printf "%s\n" "----------"
          bash --version
          printf "%s\n" "----------"
      - name: install perl modules
        run: |
          cpanm --notest Test::More
          cpanm --notest Data::Dumper
          cpanm --notest JSON
          cpanm --notest Text::Diff
      - name: run it
        run: |
          ./testssl.sh -R --debug 1 https://81.169.166.184
          cat /tmp/testssl.*/81.169.166.184.run_renego.errorlog
          printf "%s\n" "----------"
          printf "%s\n" "----------"
          cat /tmp/testssl.*/81.169.166.184.run_renego.txt
          
